global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'cardano-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s
    # scrape_timeout: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  # - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    # static_configs:
      # - targets: ['localhost:9100']

  - job_name: 'Cardano'

    static_configs:
      - targets: ['localhost:9100']

        labels:
          alias: 'relaynode1'
          type:  'cardano-node'

      #- targets: ['<relay node 2 public ip address>:9100']

       # labels:
        #  alias: 'relaynode2'
         # type:  'cardano-node'
      - targets: ['192.168.1.127:9100']

        labels:
          alias: 'block-producer-node'
          type:  'cardano-node'

      - targets: ['localhost:12798']
        labels:
          alias: 'relaynode1'
          type:  'cardano-node'
     #- targets: ['<relay node 2 public ip address>:12798']

      #  labels:
       #   alias: 'relaynode2'
        #  type:  'cardano-node'

      - targets: ['192.168.1.127:12798']
        labels:
          alias: 'block-producer-node'
          type:  'cardano-node'
